import fs from "node:fs";
import path from "node:path";

export type InstallerPlatform = "linux" | "macos";
export type InstallerArchitecture = "x86_64" | "aarch64";

const artifactNames: Record<InstallerPlatform, Record<InstallerArchitecture, string>> = {
  linux: {
    x86_64: "scout-agent-linux-x86_64",
    aarch64: "scout-agent-linux-aarch64",
  },
  macos: {
    x86_64: "scout-agent-macos-x86_64",
    aarch64: "scout-agent-macos-aarch64",
  },
};

export function artifactName(
  platform: InstallerPlatform,
  architecture: InstallerArchitecture,
): string {
  return artifactNames[platform][architecture];
}

export function artifactPath(
  platform: InstallerPlatform,
  architecture: InstallerArchitecture,
): string {
  const artifactDirectory =
    process.env.SCOUT_AGENT_ARTIFACT_DIR ?? path.join(process.cwd(), "agent-artifacts");
  return path.join(
    /*turbopackIgnore: true*/ artifactDirectory,
    artifactName(platform, architecture),
  );
}

export function readAgentArtifact(
  platform: InstallerPlatform,
  architecture: InstallerArchitecture,
): Buffer | null {
  try {
    return fs.readFileSync(/*turbopackIgnore: true*/ artifactPath(platform, architecture));
  } catch (error) {
    if (error instanceof Error && (error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

export function renderInstallerScript(input: {
  serverUrl: string;
  callbackUrl: string;
  invitation: string;
  agentVersion?: string;
  publisherPublicKey?: string;
  requireHttpTrustPin?: boolean;
}): string {
  const serverUrl = shellQuote(input.serverUrl);
  const callbackUrl = shellQuote(input.callbackUrl);
  const invitation = shellQuote(input.invitation);
  const agentVersion = shellQuote(input.agentVersion ?? "0.1.0");
  const publisherPublicKey = shellQuote(input.publisherPublicKey ?? "");
  const requireHttpTrustPin = input.requireHttpTrustPin === true ? "1" : "0";
  const lines = [
    "#!/bin/sh",
    "set -eu",
    "",
    "SCOUT_SERVER_URL=${SCOUT_SERVER_URL:-" + serverUrl + "}",
    "SCOUT_CALLBACK_URL=${SCOUT_CALLBACK_URL:-" + callbackUrl + "}",
    "SCOUT_OTI=${SCOUT_OTI:-" + invitation + "}",
    "SCOUT_AGENT_VERSION=${SCOUT_AGENT_VERSION:-" + agentVersion + "}",
    "SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY=${SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY:-" +
      publisherPublicKey +
      "}",
    "SCOUT_AGENT_ROOT=${SCOUT_AGENT_ROOT:-/var/lib/scout-agent}",
    "SCOUT_PRIVILEGE_FILE=${SCOUT_PRIVILEGE_FILE:-}",
    `SCOUT_REQUIRE_TRUST_PIN=${requireHttpTrustPin}`,
    "SCOUT_TRUST_PIN=${SCOUT_TRUST_PIN:-}",
    "",
    "fail() {",
    "  printf '%s\\n' \"scout-agent installer: $1\" >&2",
    "  exit 1",
    "}",
    "",
    "fetch_to() {",
    "  url=$1",
    "  destination=$2",
    "  if command -v curl >/dev/null 2>&1; then",
    "    curl --fail --silent --show-error --location --retry 2 \\",
    '      --header "x-scout-oti: $SCOUT_OTI" "$url" -o "$destination"',
    "  elif command -v wget >/dev/null 2>&1; then",
    '    wget --quiet --output-document="$destination" \\',
    '      --header="x-scout-oti: $SCOUT_OTI" "$url"',
    "  else",
    '    fail "curl or wget is required"',
    "  fi",
    "}",
    "",
    'if [ -z "$SCOUT_SERVER_URL" ] || [ -z "$SCOUT_OTI" ]; then',
    '  fail "server URL and one-time invitation are required"',
    "fi",
    "",
    'if [ "$SCOUT_REQUIRE_TRUST_PIN" = 1 ]; then',
    '  case "$SCOUT_SERVER_URL" in',
    "    http://*)",
    '      [ -n "$SCOUT_TRUST_PIN" ] || fail "SCOUT_TRUST_PIN is required for HTTP bootstrap"',
    '      trust_response="${TMPDIR:-/tmp}/scout-trust.$$"',
    '      fetch_to "$SCOUT_SERVER_URL/api/v1/bootstrap/fingerprint" "$trust_response" || \\',
    '        fail "could not read the Scout bootstrap fingerprint"',
    '      expected_pin=$(sed -n \'s/.*"fingerprint":"\\([^"]*\\)".*/\\1/p\' "$trust_response")',
    '      rm -f "$trust_response"',
    '      [ "$expected_pin" = "$SCOUT_TRUST_PIN" ] || fail "Scout bootstrap fingerprint does not match SCOUT_TRUST_PIN"',
    "      ;;",
    "  esac",
    "fi",
    "",
    'preflight="${TMPDIR:-/tmp}/scout-preflight.$$"',
    'fetch_to "$SCOUT_CALLBACK_URL/api/v1/bootstrap/agent/preflight" "$preflight" || \\',
    '  fail "Scout callback is unreachable at $SCOUT_CALLBACK_URL; set SCOUT_PUBLIC_URL to a URL reachable from this host"',
    'rm -f "$preflight"',
    "",
    "os=$(uname -s 2>/dev/null || true)",
    "machine=$(uname -m 2>/dev/null || true)",
    'case "$os:$machine" in',
    "  Linux:x86_64|Linux:amd64) platform=linux; architecture=x86_64 ;;",
    "  Linux:aarch64|Linux:arm64) platform=linux; architecture=aarch64 ;;",
    "  Darwin:x86_64|Darwin:amd64) platform=macos; architecture=x86_64 ;;",
    "  Darwin:arm64|Darwin:aarch64) platform=macos; architecture=aarch64 ;;",
    '  *) fail "unsupported platform or architecture: $os $machine" ;;',
    "esac",
    "",
    'tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/scout-agent.XXXXXX")',
    "lock_dir=/var/lock/scout-agent-install.lock",
    "lock_acquired=0",
    "cleanup() {",
    '  if [ "$lock_acquired" = 1 ]; then release_install_lock; fi',
    '  rm -rf "$tmp_dir"',
    "}",
    "trap cleanup EXIT HUP INT TERM",
    "",
    'artifact="$tmp_dir/scout-agent"',
    'fetch_to "$SCOUT_SERVER_URL/api/v1/bootstrap/agent/artifact?platform=$platform&architecture=$architecture" "$artifact" || \\',
    '  fail "Scout has no verified agent artifact for $platform/$architecture"',
    'chmod 700 "$artifact"',
    "",
    "run_privileged() {",
    '  if [ "$(id -u)" -eq 0 ]; then',
    '    "$@"',
    "  elif command -v sudo >/dev/null 2>&1; then",
    '    if [ -n "$SCOUT_PRIVILEGE_FILE" ] && [ -s "$SCOUT_PRIVILEGE_FILE" ]; then',
    '      sudo -S -p \'\' "$@" < "$SCOUT_PRIVILEGE_FILE"',
    "    else",
    '      sudo "$@"',
    "    fi",
    "  else",
    '    fail "root or sudo access is required"',
    "  fi",
    "}",
    "",
    "release_install_lock() {",
    '  run_privileged rmdir "$lock_dir" 2>/dev/null || true',
    "}",
    "",
    "acquire_install_lock() {",
    "  run_privileged sh -c '",
    "    lock=$1; pid=$2",
    '    if mkdir "$lock" 2>/dev/null; then printf "%s\\n" "$pid" > "$lock/pid"; exit 0; fi',
    '    owner=$(cat "$lock/pid" 2>/dev/null || true)',
    '    case "$owner" in',
    '      ""|*[!0-9]*) exit 1 ;;',
    '      *) kill -0 "$owner" 2>/dev/null && exit 1 ;;',
    "    esac",
    '    rm -rf "$lock" && mkdir "$lock" && printf "%s\\n" "$pid" > "$lock/pid"',
    '  \' scout-lock "$lock_dir" "$$" || fail "another Scout agent installation is already running"',
    "  lock_acquired=1",
    "}",
    "",
    "activate_current() {",
    '  current_link="$SCOUT_AGENT_ROOT/current"',
    '  temporary_link="$current_link.tmp.$$"',
    '  run_privileged rm -f "$temporary_link"',
    '  run_privileged ln -s "$release_dir" "$temporary_link"',
    '  run_privileged mv -f "$temporary_link" "$current_link"',
    "}",
    "",
    'launcher="$tmp_dir/scout-agent-launcher"',
    "cat > \"$launcher\" <<'EOF'",
    "#!/bin/sh",
    "set -eu",
    "agent_root=${SCOUT_AGENT_ROOT:-/var/lib/scout-agent}",
    'current="$agent_root/current/scout-agent"',
    "rollback_current() {",
    '  previous_version=$(cat "$agent_root/previous" 2>/dev/null || true)',
    '  case "$previous_version" in',
    '    ""|*[!A-Za-z0-9._-]*) return 1 ;;',
    "  esac",
    '  temporary="$agent_root/current.rollback.$$"',
    '  rm -f "$temporary"',
    '  ln -s "releases/$previous_version" "$temporary"',
    '  mv -f "$temporary" "$agent_root/current"',
    '  rm -f "$agent_root/previous"',
    "}",
    'if [ -f "$agent_root/previous" ]; then',
    '  if ! "$current" "$@" --once; then rollback_current || true; fi',
    "fi",
    'exec "$current" "$@"',
    "EOF",
    "",
    "acquire_install_lock",
    "",
    "run_agent_once() {",
    '  if [ "$(id -u)" -eq 0 ]; then',
    '    SCOUT_SERVER_URL="$SCOUT_SERVER_URL" SCOUT_INVITATION="$SCOUT_OTI" \\',
    '      SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY="$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY" SCOUT_AGENT_ROOT="$SCOUT_AGENT_ROOT" \\',
    '      SCOUT_DATA_DIR="$1" "$2" --once',
    "  else",
    '    run_privileged env SCOUT_SERVER_URL="$SCOUT_SERVER_URL" SCOUT_INVITATION="$SCOUT_OTI" \\',
    '      SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY="$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY" SCOUT_AGENT_ROOT="$SCOUT_AGENT_ROOT" \\',
    '      SCOUT_DATA_DIR="$1" "$2" --once',
    "  fi",
    "}",
    "",
    "runuser_binary=$(command -v runuser 2>/dev/null || true)",
    'if [ -z "$runuser_binary" ]; then',
    "  for candidate in /usr/sbin/runuser /sbin/runuser; do",
    '    if [ -x "$candidate" ]; then runuser_binary="$candidate"; break; fi',
    "  done",
    "fi",
    "",
    "run_linux_agent_once() {",
    '  if [ "$(id -u)" -eq 0 ]; then',
    '    "$runuser_binary" -u scout-agent -- env SCOUT_SERVER_URL="$SCOUT_SERVER_URL" \\',
    '      SCOUT_INVITATION="$SCOUT_OTI" SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY="$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY" \\',
    '      SCOUT_AGENT_ROOT="$SCOUT_AGENT_ROOT" SCOUT_DATA_DIR="$1" "$2" --once',
    "  elif command -v sudo >/dev/null 2>&1; then",
    '    if [ -n "$SCOUT_PRIVILEGE_FILE" ] && [ -s "$SCOUT_PRIVILEGE_FILE" ]; then',
    "      sudo -S -p '' -u scout-agent env SCOUT_SERVER_URL=\"$SCOUT_SERVER_URL\" \\",
    '        SCOUT_INVITATION="$SCOUT_OTI" SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY="$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY" \\',
    '        SCOUT_AGENT_ROOT="$SCOUT_AGENT_ROOT" SCOUT_DATA_DIR="$1" "$2" --once < "$SCOUT_PRIVILEGE_FILE"',
    "    else",
    '      sudo -u scout-agent env SCOUT_SERVER_URL="$SCOUT_SERVER_URL" \\',
    '        SCOUT_INVITATION="$SCOUT_OTI" SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY="$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY" \\',
    '        SCOUT_AGENT_ROOT="$SCOUT_AGENT_ROOT" SCOUT_DATA_DIR="$1" "$2" --once',
    "    fi",
    "  else",
    '    fail "root or sudo access is required to initialize the Scout agent"',
    "  fi",
    "}",
    "",
    'case "$platform" in',
    "  linux)",
    '    [ -n "$runuser_binary" ] || fail "runuser is required for the Linux service account"',
    "    SCOUT_AGENT_ROOT=/var/lib/scout-agent",
    '    release_dir="$SCOUT_AGENT_ROOT/releases/$SCOUT_AGENT_VERSION"',
    '    run_privileged install -d -m 0755 "$release_dir" "$SCOUT_AGENT_ROOT" /usr/local/lib/scout-agent',
    '    run_privileged install -m 0755 "$artifact" "$release_dir/scout-agent"',
    '    run_privileged install -m 0755 "$launcher" /usr/local/lib/scout-agent/scout-agent-launcher',
    "    activate_current",
    "    if ! getent passwd scout-agent >/dev/null 2>&1; then",
    "      run_privileged useradd --system --home-dir /var/lib/scout-agent --shell /usr/sbin/nologin scout-agent",
    "    fi",
    "    run_privileged chown -R scout-agent:scout-agent /var/lib/scout-agent",
    "    run_privileged install -d -m 0755 /etc/systemd/system",
    '    unit="$tmp_dir/scout-agent.service"',
    '    cat > "$unit" <<EOF',
    "[Unit]",
    "Description=Scout host monitoring agent",
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    "User=scout-agent",
    "Environment=SCOUT_AGENT_ROOT=/var/lib/scout-agent",
    "Environment=SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY=$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY",
    "ExecStart=/usr/local/lib/scout-agent/scout-agent-launcher --server $SCOUT_SERVER_URL --data-dir /var/lib/scout-agent",
    "Restart=always",
    "RestartSec=5",
    "NoNewPrivileges=true",
    "ProtectSystem=strict",
    "ProtectHome=true",
    "ReadWritePaths=/var/lib/scout-agent",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "EOF",
    '    run_privileged install -m 0644 "$unit" /etc/systemd/system/scout-agent.service',
    "    run_linux_agent_once /var/lib/scout-agent /usr/local/lib/scout-agent/scout-agent-launcher",
    "    run_privileged systemctl daemon-reload",
    "    run_privileged systemctl enable --now scout-agent.service",
    "    ;;",
    "  macos)",
    '    SCOUT_AGENT_ROOT="/Library/Application Support/ScoutAgent"',
    '    release_dir="$SCOUT_AGENT_ROOT/releases/$SCOUT_AGENT_VERSION"',
    '    run_privileged install -d -m 0755 "$release_dir" \\',
    '      "$SCOUT_AGENT_ROOT" /usr/local/lib/scout-agent',
    '    run_privileged install -m 0755 "$artifact" "$release_dir/scout-agent"',
    '    run_privileged install -m 0755 "$launcher" /usr/local/lib/scout-agent/scout-agent-launcher',
    "    activate_current",
    '    run_agent_once "/Library/Application Support/ScoutAgent" /usr/local/lib/scout-agent/scout-agent-launcher',
    '    plist="$tmp_dir/page.rtin.scout-agent.plist"',
    '    cat > "$plist" <<EOF',
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0"><dict>',
    "  <key>Label</key><string>page.rtin.scout-agent</string>",
    "  <key>ProgramArguments</key><array>",
    "    <string>/usr/local/lib/scout-agent/scout-agent-launcher</string><string>--server</string><string>$SCOUT_SERVER_URL</string><string>--data-dir</string><string>/Library/Application Support/ScoutAgent</string>",
    "  </array>",
    "  <key>EnvironmentVariables</key><dict>",
    "    <key>SCOUT_AGENT_ROOT</key><string>/Library/Application Support/ScoutAgent</string>",
    "    <key>SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY</key><string>$SCOUT_RELEASE_PUBLISHER_PUBLIC_KEY</string>",
    "  </dict>",
    "  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>",
    "</dict></plist>",
    "EOF",
    '    run_privileged install -m 0644 "$plist" /Library/LaunchDaemons/page.rtin.scout-agent.plist',
    "    run_privileged launchctl bootout system /Library/LaunchDaemons/page.rtin.scout-agent.plist 2>/dev/null || true",
    "    run_privileged launchctl bootstrap system /Library/LaunchDaemons/page.rtin.scout-agent.plist",
    "    ;;",
    "esac",
    "",
    "printf '%s\\n' \"Scout agent installed and enrolled.\"",
  ];
  return lines.join("\n") + "\n";
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}
