import { useEffect, useState } from "react";
import { Activity, CircleHelp, Download, LayoutList, Network, Radio, Terminal } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { api, type Device } from "@/lib/api";
import { SetupView } from "@/views/setup";
import { SystemsView } from "@/views/systems";
import { DeviceView } from "@/views/device";
import { NetworkView } from "@/views/network";
import { UpdatesView } from "@/views/updates";

type Page = "Systems" | "Network" | "Updates";
const pages = [{name:"Systems" as const,icon:LayoutList},{name:"Network" as const,icon:Network},{name:"Updates" as const,icon:Download}];

export default function App() {
  const [auth,setAuth]=useState<"loading"|"signedOut"|"signedIn">("loading");const [page,setPage]=useState<Page>("Systems");const [demo,setDemo]=useState(false);const [query,setQuery]=useState("");const [selected,setSelected]=useState<Device|null>(null);const [help,setHelp]=useState(false);const [status,setStatus]=useState<{mode:string;database:string}|null>(null);const [statusError,setStatusError]=useState(false);
  useEffect(()=>{let cancelled=false;api.owner().then(()=>{if(!cancelled)setAuth("signedIn")}).catch(()=>{if(!cancelled)setAuth("signedOut")});api.status().then((value)=>{if(!cancelled)setStatus(value)}).catch(()=>{if(!cancelled)setStatusError(true)});return()=>{cancelled=true}},[]);
  if(auth!=="signedIn")return <><header className="topbar auth-topbar"><a className="brand" href="/" onClick={(event)=>event.preventDefault()}><Radio size={24}/><span>Scout</span></a><Badge variant="outline">{status?.mode??"Self-hosted"}</Badge></header><SetupView onSignedIn={()=>setAuth("signedIn")}/></>;
  function navigate(next:Page){setPage(next);setSelected(null);setQuery("")}
  return <div className="app-shell"><header className="topbar"><a href="#" className="brand" onClick={(event)=>{event.preventDefault();navigate("Systems")}}><Radio size={24}/><span>Scout</span></a><span className="workspace-name">Personal network</span><div className="topbar-actions"><Badge variant="outline">{status?.mode??"Self-hosted"}</Badge><Button variant="ghost" size="icon" aria-label="Setup information" aria-expanded={help} onClick={()=>setHelp(!help)}><CircleHelp size={18}/></Button><div className="avatar" title="Single-owner workspace">O</div></div></header><div className="toolbar"><nav aria-label="Main navigation">{pages.map(({name,icon:Icon})=><button key={name} className={page===name?"active":""} aria-current={page===name?"page":undefined} onClick={()=>navigate(name)}><Icon size={16}/>{name}</button>)}</nav><Button variant="outline" size="sm" onClick={()=>{setDemo(!demo);setSelected(null);setQuery("")}}>{demo?<Activity size={14}/>:<Radio size={14}/>} {demo?"Exit demo":"Explore demo"}</Button></div><main>{demo&&<div className="notice demo-notice"><Activity size={15}/><span>Demo workspace. Devices, metrics, and network relationships are illustrative and never enter operational storage.</span><Badge variant="outline">Sample data</Badge></div>}{help&&<section className="setup-panel"><div><Terminal size={21}/><h2>First Linux agent</h2></div><p>Use protected owner setup, then create a one-time invitation. The agent sends real observations over its authenticated outbound connection.</p><code>scout-agent --daemon --invitation-file /run/scout/invitation</code><Button variant="outline" size="sm" onClick={()=>setHelp(false)}>Close</Button></section>}{selected?<DeviceView selected={selected} demo={demo} onBack={()=>setSelected(null)}/>:<><div className="page-heading"><div><h1>{page==="Systems"?"All systems":page==="Network"?"Network map":"Agent updates"}</h1><p>{page==="Systems"?"Every machine. One clear view.":page==="Network"?"Understand how infrastructure connects, with evidence.":"Keep agents current, including on isolated networks."}</p></div>{page==="Systems"&&<Button variant="outline" onClick={()=>setHelp(true)}><Terminal size={15}/>Agent setup</Button>}</div>{page==="Systems"&&<SystemsView demo={demo} query={query} onQuery={setQuery} onSelect={setSelected} onSetup={()=>setHelp(true)}/>} {page==="Network"&&<NetworkView demo={demo} onSelect={setSelected}/>} {page==="Updates"&&<UpdatesView/>}</>}</main><footer className="footer"><span>Self-hosted · single owner</span><div aria-live="polite">{statusError?<><span className="dot amber"/>API unavailable</>:<><span className={`dot ${status?.database==="connected"?"healthy":"muted"}`}/>{status?`API ${status.database}`:"Connecting to API…"}</>}</div></footer></div>;
}
