import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { ArrowLeft, ChartNoAxesCombined, HardDrive, MemoryStick, Server, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { api, APIError, type Device, type MetricSeries } from "@/lib/api";

function latest(device: Device, metric: string): number | null { const item=device.currentMetrics?.[metric];return item&&typeof item.value==="number"?item.value:null; }
function demoSeries(base: number, seed: number): Array<{time:number;value:number|null;availability:string}> { return Array.from({length:61},(_,i)=>({time:i-60,value:i===60?base:Number(Math.min(97,Math.max(2,base+Math.sin(i*.78+seed)*5+(i>37&&i<44?24:0))).toFixed(1)),availability:"current"})); }

export function DeviceView({ selected, demo, onBack }: { selected: Device; demo: boolean; onBack: ()=>void }) {
  const [device,setDevice]=useState(selected);const [series,setSeries]=useState<MetricSeries[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(!demo);
  useEffect(()=>{if(demo)return;let cancelled=false;setLoading(true);Promise.all([api.device(selected.id),api.metrics(selected.id)]).then(([detail,metrics])=>{if(cancelled)return;setDevice(detail);setSeries(metrics.series)}).catch((caught)=>{if(!cancelled)setError(caught instanceof APIError?caught.message:"Could not load host history")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[demo,selected.id]);
  const cpu=latest(device,"cpu.utilization")??0;const memory=latest(device,"memory.used_percent")??0;const disk=latest(device,"filesystem.used_percent")??0;
  const chartData=useMemo(()=>{if(demo)return {cpu:demoSeries(cpu,1),memory:demoSeries(memory,3),disk:demoSeries(disk,7)};const fromServer=series[0]?.points??[];return {cpu:fromServer.map((point)=>({time:new Date(point.observedAt).getTime(),value:point.value,availability:point.availability})),memory:[],disk:[]}},[demo,series,cpu,memory,disk]);
  return <><Button className="back" variant="ghost" size="sm" onClick={onBack}><ArrowLeft size={15} />All systems</Button><div className="page-heading"><div><h1>{device.displayName}</h1><p><span className={`dot ${device.availability==="online"?"healthy":"muted"}`} />{device.availability} <span className="divider">/</span> {device.addresses[0]??"Address unavailable"} <span className="divider">/</span> {device.platform} {device.architecture}</p></div><Badge variant="outline">{demo?"Last hour · demo":loading?"Loading history":"Last hour"}</Badge></div>
    {error&&<div className="notice error-notice" role="alert"><ShieldCheck size={15}/><span>{error}</span></div>}
    {device.availability!=="online"&&device.agentVersion&&<div className="notice stale-notice" role="status"><Server size={15}/><span>Agent {device.availability}; retained measurements remain historical and are not current.</span></div>}
    {device.agentVersion&&device.availability!=="revoked"?<div className="charts"><MetricChart title="CPU usage" detail="Utilization across all cores" unit="percent" color="#7392f5" data={chartData.cpu} current={cpu} /><MetricChart title="Memory usage" detail="Used memory as a share of total" unit="percent" color="#62b697" data={chartData.memory.length?chartData.memory:demo?chartData.memory:[]} current={memory} /><MetricChart title="Disk usage" detail="Used space on the root filesystem" unit="percent" color="#ac8fd9" data={chartData.disk.length?chartData.disk:demo?chartData.disk:[]} current={disk} /><section className="chart-panel host-info"><h3>Agent</h3><dl><div><dt>Version</dt><dd>{device.agentVersion}</dd></div><div><dt>Platform</dt><dd>{device.platform} / {device.architecture}</dd></div><div><dt>Availability</dt><dd>{device.availability}</dd></div><div><dt>Last heartbeat</dt><dd>{device.lastHeartbeat?new Date(device.lastHeartbeat).toLocaleString():"Not received"}</dd></div></dl></section></div>:<div className="empty"><Server/><h2>{device.availability==="offline"?"Agent offline":device.availability==="revoked"?"Agent revoked":"Agent not installed"}</h2><p>{device.availability==="offline"?"Current metrics are unavailable. Historical values remain accessible with gaps.":"This candidate needs an authorized, trusted enrollment."}</p></div>}
  </>;
}

function MetricChart({title,detail,unit,color,data,current}:{title:string;detail:string;unit:string;color:string;data:Array<{time:number;value:number|null;availability:string}>;current:number;}) { const hasGap=data.some((point)=>point.value===null||point.availability!=="current");return <section className="chart-panel"><div className="chart-heading"><div><h3>{title}</h3><p>{detail}{hasGap?" · gaps indicate unavailable samples":""}</p></div><strong>{data.length?current.toFixed(1):"—"}<small>{data.length?` ${unit}`:""}</small></strong></div><ChartContainer config={{usage:{label:title,color}}} className="h-[200px] w-full aspect-auto" aria-label={`${title} history with units ${unit}${hasGap?", including unavailable gaps":""}`}><AreaChart accessibilityLayer data={data} margin={{top:8,right:12,left:0,bottom:4}}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="time" type="number" domain={data.length?(["dataMin","dataMax"] as [string,string]):[0,1]} ticks={data.length?[data[0]?.time??0,data[data.length-1]?.time??1]:[]} tickLine={false} axisLine={false} tickFormatter={(value)=>data.length?new Date(value).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"No samples"}/><YAxis domain={[0,100]} ticks={[0,50,100]} width={37} tickLine={false} axisLine={false} tickFormatter={(value)=>`${value}%`}/><ChartTooltip content={<ChartTooltipContent labelFormatter={(value)=>data.length?new Date(Number(value)).toLocaleString():"Sample time unavailable"} formatter={(value)=>value==null?<span>Unavailable</span>:<span>{title}<strong>{Number(value).toFixed(1)}%</strong></span>} />}/><Area dataKey="value" type="linear" stroke="var(--color-usage)" fill="var(--color-usage)" fillOpacity={.2} strokeWidth={1.7} connectNulls={false} isAnimationActive={false}/></AreaChart></ChartContainer></section>; }

export function metricIcon(metric:string){if(metric.includes("memory"))return MemoryStick;if(metric.includes("disk")||metric.includes("filesystem"))return HardDrive;return ChartNoAxesCombined;}
