import { useEffect, useState } from "react";
import { Network as NetworkIcon, Server } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { api, APIError, type Device } from "@/lib/api";
import { demoDevices } from "@/demo";

export function NetworkView({ demo, onSelect }: { demo: boolean; onSelect: (device: Device)=>void }) {
  const [nodes,setNodes]=useState<Array<Record<string,unknown>>>([]);const [relationships,setRelationships]=useState<Array<Record<string,unknown>>>([]);const [error,setError]=useState("");
  useEffect(()=>{if(demo)return;let cancelled=false;api.topology().then((result)=>{if(!cancelled){setNodes(result.nodes);setRelationships(result.relationships)}}).catch((caught)=>{if(!cancelled)setError(caught instanceof APIError?caught.message:"Could not load topology")});return()=>{cancelled=true}},[demo]);
  const demoNodes=demo?demoDevices.map((device,index)=>({id:`demo-${index}`,label:device.name,addresses:[device.address],availability:device.status.toLowerCase()})):nodes;
  return <section className="network-panel"><div className="map-header"><Badge variant="outline">Evidence-backed</Badge><span>{demo?"Illustrative observations · not physical cabling":"Relationships expire unless refreshed; inspect source and age."}</span></div>{error&&<div className="empty" role="alert"><NetworkIcon size={32}/><h2>Topology unavailable</h2><p>{error}</p><Button variant="outline" onClick={()=>location.reload()}>Retry</Button></div>}{!error&&<><div className="map-root"><NetworkIcon size={22}/><strong>{demo?"Lab network":"Scout network"}</strong><span>{demoNodes.length} observed devices</span></div><div className="map-devices" role="list" aria-label="Topology nodes">{demo?demoDevices.map((device,index)=><button key={device.name} onClick={()=>onSelect({id:`demo-${index}`,displayName:device.name,platform:"linux",architecture:"amd64",addresses:[device.address],lifecycle:"enrolled",availability:device.status==="Offline"?"offline":"online",metricFreshness:{},collectorStates:[],revision:1})} role="listitem"><Server size={20}/><strong>{device.name}</strong><small>{device.address}</small><span className={`dot ${device.status==="Healthy"?"healthy":device.status==="Offline"?"muted":"amber"}`} /> </button>):demoNodes.map((node)=><div className="topology-node" key={String(node.id)} role="listitem"><Server size={20}/><strong>{String(node.label??node.id)}</strong><small>{Array.isArray(node.addresses)?node.addresses.join(", "):"Address unavailable"}</small><span>{String(node.availability??"unknown")}</span></div>)}</div><div className="evidence-list" aria-label="Topology evidence">{demo? <p>Demo relationship evidence is isolated and labeled. Logical membership is not confirmed physical cabling.</p>:relationships.length?relationships.map((relationship,index)=><div key={String(relationship.id??index)}><strong>{String(relationship.type??"relationship")}</strong><span>{String(relationship.source??"source unavailable")} · {String(relationship.confidence??"unknown")} confidence</span><small>{String(relationship.observedAt??"observation time unavailable")} · expires {String(relationship.expiresAt??"unknown")}</small></div>):<p>No relationships have been observed yet.</p>}</div></>}</section>;
}
