import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Cpu, HardDrive, MemoryStick, Network, Radio, Search, Server } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { api, APIError, type Device } from "@/lib/api";
import { demoDevices, type Device as DemoDevice } from "@/demo";

function Meter({ value }: { value: number }) { return <div className="meter"><span>{value.toFixed(1)}<small>%</small></span><div className="track"><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }} className={value >= 80 ? "warning" : ""} /></div></div>; }
function liveValue(device: Device, metric: string): number | null { const value=device.currentMetrics?.[metric]?.value; return typeof value === "number" ? value : null; }
function stateLabel(device: Device): string { if (device.lifecycle === "decommissioned" || device.availability === "revoked") return "Revoked"; if (!device.agentVersion) return "Needs access"; if (device.availability === "offline") return "Offline"; if (device.availability === "connecting") return "Connecting"; return "Online"; }
function demoToLive(item: DemoDevice, index: number): Device { return { id: `demo-${index}`, displayName:item.name, platform:"linux", architecture:"amd64", lifecycle:"enrolled", addresses:[item.address], agentVersion:item.version === "—" ? undefined : item.version, availability:item.status === "Offline" ? "offline" : "online", metricFreshness:{}, currentMetrics:{"cpu.utilization":{value:item.cpu,unit:"percent",availability:"current",observedAt:new Date().toISOString()},"memory.used_percent":{value:item.memory,unit:"percent",availability:"current",observedAt:new Date().toISOString()},"filesystem.used_percent":{value:item.disk,unit:"percent",availability:"current",observedAt:new Date().toISOString()}}, collectorStates:[], revision:1 } as Device; }

export function SystemsView({ demo, query, onQuery, onSelect, onSetup }: { demo: boolean; query: string; onQuery: (value: string) => void; onSelect: (device: Device) => void; onSetup: () => void }) {
  const [items, setItems] = useState<Device[]>([]); const [loading, setLoading] = useState(!demo); const [error, setError] = useState(""); const [retry, setRetry] = useState(0);
  useEffect(() => { if (demo) return; let cancelled=false;setLoading(true);setError("");api.devices().then((result)=>{if(!cancelled)setItems(result.items)}).catch((caught)=>{if(!cancelled)setError(caught instanceof APIError?caught.message:"Could not load systems")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[demo,retry]);
  const devices = demo ? demoDevices.map(demoToLive) : items;
  const filtered = useMemo(() => devices.filter((device) => `${device.displayName} ${device.hostname ?? ""} ${device.addresses.join(" ")} ${stateLabel(device)} ${device.platform}`.toLowerCase().includes(query.toLowerCase())), [devices, query]);
  const counts = { online:devices.filter((d)=>stateLabel(d)==="Online").length, offline:devices.filter((d)=>stateLabel(d)==="Offline").length, access:devices.filter((d)=>stateLabel(d)==="Needs access").length };
  return <section className="systems-panel">
    <div className="panel-toolbar"><div className="summary"><span><i className="dot healthy" />{counts.online} online</span><span><i className="dot muted" />{counts.offline} offline</span><span><i className="dot amber" />{counts.access} needs access</span></div><div className="search-field"><Search size={15} /><Input aria-label="Filter systems" placeholder="Filter systems…" value={query} onChange={(event)=>onQuery(event.target.value)} /></div></div>
    {loading ? <div className="empty" role="status"><Radio size={30} /><h2>Loading systems</h2><p>Reading authenticated inventory…</p></div> : error ? <div className="empty" role="alert"><Radio size={30} /><h2>Systems unavailable</h2><p>{error}</p><Button variant="outline" onClick={()=>setRetry((value)=>value+1)}>Retry</Button></div> : <>
      <div className="table-scroll"><table><thead><tr><th><Server />System</th><th><Cpu />CPU</th><th><MemoryStick />Memory</th><th><HardDrive />Disk</th><th><Network />Network</th><th><Radio />State</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.map((device)=><SystemRow key={device.id} device={device} onSelect={onSelect} />)}</tbody></table></div>
      {!filtered.length && <div className="empty"><div className="empty-icon"><Radio size={30} /></div><h2>{query?"No matching systems":"Your network starts here"}</h2><p>{query?"Try a hostname, IP address, or status label.":"Connect your first Linux agent to start building a picture of your network."}</p><Button variant="outline" onClick={()=>query?onQuery(""):onSetup()}>{query?"Clear filter":"Agent setup"}<ArrowUpRight size={14} /></Button>{!query&&!demo&&<small>Operational data stays separate from demo mode.</small>}</div>}
      <div className="table-footer"><span>{filtered.length} systems{demo?" · illustrative data":""}</span><span>One agent per device</span></div>
    </>}
  </section>;
}

function SystemRow({ device, onSelect }: { device: Device; onSelect: (device: Device)=>void }) { const state=stateLabel(device);const cpu=liveValue(device,"cpu.utilization");const memory=liveValue(device,"memory.used_percent");const disk=liveValue(device,"filesystem.used_percent");return <tr><td><button className="device-link" onClick={()=>onSelect(device)}><i className={`dot ${state==="Online"?"healthy":state==="Needs access"?"amber":"muted"}`} /><span><strong>{device.displayName}</strong><small>{device.addresses[0] ?? device.hostname ?? "Address unavailable"}</small></span></button></td><td>{cpu===null?<span className="no-value">—</span>:<Meter value={cpu} />}</td><td>{memory===null?<span className="no-value">—</span>:<Meter value={memory} />}</td><td>{disk===null?<span className="no-value">—</span>:<Meter value={disk} />}</td><td className="network-value"><span className="no-value">—</span></td><td><Badge variant="outline" className={state==="Needs access"?"access-label":"version"}>{state}</Badge>{device.agentVersion&&<small className="version-detail">v{device.agentVersion}</small>}</td><td><Button variant="ghost" size="icon" aria-label={`View ${device.displayName}`} onClick={()=>onSelect(device)}><ArrowUpRight size={15} /></Button></td></tr>; }
